### PR TITLE
Meme data api

### PR DESCRIPTION
**Pull request by xiningchen**
- Need this PR in order for voting to work

### CODE REVIEW

**Comment by xiningchen** [comment]
It's needed because before, when a vote gets changed, I pass to the Frontend a String message. That causes issues in changing votes. This PR changes the message to the MemeVote object which satisfies the promise in the meme service.

**Comment by Step7750** [comment]
I think the frontend should be changed instead then. It shouldn't need this reply since if the promise resolves, you know the action was completed.

**Comment by xiningchen** [comment]
The promise is not resolved. The promise promises a MemeVote, but even in the case that it succeeds, a message is passed back and so the service doesn't think it's a meme-vote. This solves that. In addition, it doesn't help to pass the message "Your vote has been updated".

**Comment by Step7750** [comment]
If the `then` handler gets called, then the promise resolves. Therefore, the request must have succeeded and the calling code will know that without having to return anything. The interface for what the MemeVote returns could just be the generic message.

**Comment by xiningchen** [comment]
But why not just return the memeVote object itself? Why is it better for the server to return a generic message that doesn't contain much information?

**Pull request closed without merging**
